name: Deploy to Website

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Add Azure VM to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H 74.249.8.238 >> ~/.ssh/known_hosts
        
    - name: Sync files to Azure VM
      run: |
        rsync -av --delete ./ ashutosh@74.249.8.238:/home/ashutosh/var/www/html/


